name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        node-version: 14  # ou qualquer versão mais recente que suporta Node.js 16

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0  # ou a versão do .NET que você está usando

    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Build and Push Docker Image
      run: |
        docker-compose build
        docker tag apimysqldocker:latest 977535253370.dkr.ecr.us-east-1.amazonaws.com/intervaloverity:latest
        docker push 977535253370.dkr.ecr.us-east-1.amazonaws.com/intervaloverity:latest
        docker tag mysql:8.0.22 977535253370.dkr.ecr.us-east-1.amazonaws.com/intervaloverity:mysql-8.0.22
        docker push 977535253370.dkr.ecr.us-east-1.amazonaws.com/intervaloverity:mysql-8.0.22

    - name: Deploy to AWS ECS
      run: |
        ecs-cli configure --cluster intervaloverity_tech --region ${{ secrets.AWS_REGION }}
        ecs-cli compose --file docker-compose.yml service up
